/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    slides: Slide;
    awards: Award;
    press: Press;
    places: Place;
    photos: Photo;
    services: Service;
    team: Team;
    videos: Video;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    slides: SlidesSelect<false> | SlidesSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    press: PressSelect<false> | PressSelect<true>;
    places: PlacesSelect<false> | PlacesSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    about: About;
    destinations: Destination;
    gallery: Gallery;
    contact: Contact;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Photos in the opening banner. Order controls the slideshow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides".
 */
export interface Slide {
  id: number;
  /**
   * Leave this empty to keep the image path below.
   */
  image?: (number | null) | Media;
  /**
   * Path on the website, for example images/banner/01.jpg
   */
  imagePath?: string | null;
  alt: string;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  line1: string;
  line2?: string | null;
  note?: string | null;
  years: string;
  /**
   * Turn this on for longer award names so they fit inside the wreath.
   */
  longName?: boolean | null;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press".
 */
export interface Press {
  id: number;
  name: string;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * International cards show a location. India cards show a venue list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places".
 */
export interface Place {
  id: number;
  region: 'international' | 'india';
  name: string;
  /**
   * Leave this empty to keep the image path below.
   */
  icon?: (number | null) | Media;
  /**
   * Path on the website, for example images/banner/01.jpg
   */
  iconPath?: string | null;
  /**
   * Name ke neeche chhoti line, jaise country ka naam. Khaali bhi chhod sakte ho.
   */
  location?: string | null;
  /**
   * Venue / hotel list. Khaali chhodoge to sirf sub line dikhegi.
   */
  venues?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  /**
   * Leave this empty to keep the image path below.
   */
  image?: (number | null) | Media;
  /**
   * Path on the website, for example images/banner/01.jpg
   */
  imagePath?: string | null;
  alt: string;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each entry becomes one tab in the Why choose us section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * For example: Wedding Films
   */
  title: string;
  body: string;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cards shown in the Creative team section on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * For example: Founder · Director
   */
  role: string;
  /**
   * Leave this empty to keep the image path below.
   */
  photo?: (number | null) | Media;
  /**
   * Path on the website, for example images/banner/01.jpg
   */
  photoPath?: string | null;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * YouTube link paste karo. Page par video apne aap play hoti hai jab scroll me aati hai.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * Koi bhi YouTube link chalega: youtube.com/watch?v=..., youtu.be/..., ya /shorts/...
   */
  youtubeUrl: string;
  caption?: string | null;
  /**
   * Lower numbers appear first on the website.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form fill karne wale yahan list mein dikhte hain. Website form is collection mein save hoti hai.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  weddingDate?: string | null;
  message?: string | null;
  status?: ('new' | 'contacted') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'slides';
        value: number | Slide;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'press';
        value: number | Press;
      } | null)
    | ({
        relationTo: 'places';
        value: number | Place;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slides_select".
 */
export interface SlidesSelect<T extends boolean = true> {
  image?: T;
  imagePath?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  line1?: T;
  line2?: T;
  note?: T;
  years?: T;
  longName?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press_select".
 */
export interface PressSelect<T extends boolean = true> {
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "places_select".
 */
export interface PlacesSelect<T extends boolean = true> {
  region?: T;
  name?: T;
  icon?: T;
  iconPath?: T;
  location?: T;
  venues?:
    | T
    | {
        name?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  image?: T;
  imagePath?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  photoPath?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  youtubeUrl?: T;
  caption?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  weddingDate?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  title: string;
  loaderKicker: string;
  /**
   * Leave this empty to keep the image path below.
   */
  logoWhite?: (number | null) | Media;
  /**
   * Path on the website, for example images/banner/01.jpg
   */
  logoWhitePath?: string | null;
  /**
   * Leave this empty to keep the image path below.
   */
  logoInk?: (number | null) | Media;
  /**
   * Path on the website, for example images/banner/01.jpg
   */
  logoInkPath?: string | null;
  edition: string;
  scrollHint: string;
  footer: string;
  tagline?: string | null;
  credit?: {
    /**
     * Jaise: Designed and Powered by
     */
    text?: string | null;
    name?: string | null;
    url?: string | null;
  };
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  whatsapp?: {
    /**
     * Country code, no + or spaces. For example 919322451778
     */
    number?: string | null;
    message?: string | null;
  };
  footerPlaces?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  nav?:
    | {
        label: string;
        /**
         * Use #cover, #about, #destinations, or #gallery.
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  pageEyebrow?: string | null;
  pageTitleGold?: string | null;
  pageTitleRest?: string | null;
  pageLede?: string | null;
  storyParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whyTitle?: string | null;
  whyLede?: string | null;
  teamTitle?: string | null;
  teamLede?: string | null;
  teamCta?: string | null;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  awardsTitle: string;
  featuredLabel: string;
  featuredIn: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  eyebrow: string;
  titleGold: string;
  titleRest: string;
  lede: string;
  /**
   * Leave this empty to keep the image path below.
   */
  background?: (number | null) | Media;
  /**
   * Path on the website, for example images/banner/01.jpg
   */
  backgroundPath?: string | null;
  internationalTitle: string;
  indiaTitle: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  eyebrow: string;
  titleGold: string;
  titleRest: string;
  lede: string;
  loadMore: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  eyebrow?: string | null;
  titleGold?: string | null;
  titleRest?: string | null;
  lede?: string | null;
  infoTitle?: string | null;
  formTitle?: string | null;
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Contact form yahan post hoti hai. Submissions Contact enquiries list mein dikhti hain. Default: /api/enquiry
   */
  formAction?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  title?: T;
  loaderKicker?: T;
  logoWhite?: T;
  logoWhitePath?: T;
  logoInk?: T;
  logoInkPath?: T;
  edition?: T;
  scrollHint?: T;
  footer?: T;
  tagline?: T;
  credit?:
    | T
    | {
        text?: T;
        name?: T;
        url?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  whatsapp?:
    | T
    | {
        number?: T;
        message?: T;
      };
  footerPlaces?:
    | T
    | {
        name?: T;
        id?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  pageEyebrow?: T;
  pageTitleGold?: T;
  pageTitleRest?: T;
  pageLede?: T;
  storyParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whyTitle?: T;
  whyLede?: T;
  teamTitle?: T;
  teamLede?: T;
  teamCta?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  awardsTitle?: T;
  featuredLabel?: T;
  featuredIn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  eyebrow?: T;
  titleGold?: T;
  titleRest?: T;
  lede?: T;
  background?: T;
  backgroundPath?: T;
  internationalTitle?: T;
  indiaTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  eyebrow?: T;
  titleGold?: T;
  titleRest?: T;
  lede?: T;
  loadMore?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  eyebrow?: T;
  titleGold?: T;
  titleRest?: T;
  lede?: T;
  infoTitle?: T;
  formTitle?: T;
  address?: T;
  email?: T;
  phone?: T;
  formAction?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}